name = "DraftsGeostatistics"
uuid = "f6297288-0a33-4cd3-a9cd-9206ac792ef7"
authors = ["Rafael Caixeta <8386288+rmcaixeta@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
